# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundamentals', '0005_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university_email',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
