# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_remove_textbook_sellingpost'),
        ('sellingPost', '0002_remove_sellingpost_textbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingpost',
            name='textbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Textbook'),
        ),
    ]
