# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPost', '0003_sellingpost_textbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingpost',
            name='sellingPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
