# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_textbook_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='image',
            field=models.CharField(default='hi', max_length=200),
            preserve_default=False,
        ),
    ]
