# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_textbook_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='klass',
            field=models.CharField(default='Chase Klass', max_length=20),
            preserve_default=False,
        ),
    ]
