# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundamentals', '0005_profile_slug'),
        ('book', '0004_textbook_klass'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingTextbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellingPrice', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('UM', 'Used with markings'), ('UN', 'Used with minimal/no markings'), ('N', 'New')], default='N', max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundamentals.Profile')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Textbook')),
            ],
        ),
    ]
