# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_sellingtextbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingtextbook',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='sellingtextbook',
            name='textbook',
        ),
        migrations.DeleteModel(
            name='SellingTextbook',
        ),
    ]
