# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPost', '0002_remove_sellingpost_textbook'),
        ('book', '0006_auto_20170731_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='sellingPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellingPost.SellingPost'),
        ),
    ]
